version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 23
    commands:
      - echo "Installing dependencies..."
      - npm ci
  build:
    commands:
      - echo "Building the React app..."
      - npm run build
  post_build:
    commands:
      - echo "Syncing build to S3..."
      - echo "Invalidating CloudFront cache..."
